### ISSUE TITLE
비즈니스 로직이 Domain에 존재하도록 Refactor

### ISSUE THREAD

**Issue by GiJungPark** [TeamDMU/DMU-BackEnd#21]
### Description
Entity에 존재하는 비즈니스 로직을 Domain으로 이전

### To-Do
- [x] Entity는 수정하지 못하도록 변경
- [x] JPA의 영속성 관리로 필드값을 변경 할 수 없기 때문에 Transaction을 사용해서 save하도록 변경
- [x] 핵심 비즈니스 로직을 Domain에 위치하도록 변경
